database-path: health_data/health_application.csv
explanations-path: health_data/explanations_health.csv

advanced-sidebar-categories: ["ID","Authors","Study Link","Main Author"]
select-deselect-all-categories: []
abstract-similarity-path: abstract_similarity_datasets/normalized_abstract_similarity_health.csv
database-similarity-path: database_similarity_datasets/normalized_database_similarity_health.csv
citation-matrix-path: interconnections_datasets/citation_matrix.csv
coauthor-matrix-path: interconnections_datasets/coauthor_matrix_health.csv



taxonomy:
  Cardio-Respiratory System:
    - Heart Rate
    - Blood Pressure
    - Blood Oxygen Saturation
    - Respiration Rate
    - Breathing Phase
    - Tidal Volume
    - Respiration Marker
    - Breathing Sound
  Mental State:
   - Emotion
   - Stress
  Nervous System:
   - Brain Activity
   - Sleep
   - Drowsiness
  Cardiovascular System:
   - Heart Rate Variation
   - Inter-Beat Interval
   - Heart Sound
   - Blood Glucose
  Disease Detection:
   - Hearing Status
   - Epileptic Seizure
  Thermal Regulation:
   - Body Temperature
  Health Tracking:
   - Cough

