database-path: health_data/health_mental_state.csv
explanations-path: health_data/explanations_health.csv

advanced-sidebar-categories: ["Leave-One-Out Cross-Validation Accuracy(LOOCV)","Main Author","Cross-Validation Accuracy(CV)","Accuracy","Precision","Recall","F1 score"]
select-deselect-all-categories: ["Year", "Health Indicator", "Sensor Position", "Sensor Type", "Physiological Signal", "Advantage"]
excluded-sidebar-categories: ["ID","Authors","Study Link"]
start-category-filters: ["Main Author", "Year","Study Link","Health Indicator","Sensor Position","Sensor Type","Physiological Signal", "Advantage"]
